import express from 'express';
import {randomUUID} from 'node:crypto';
const app=express();app.use(express.json());
const pools=new Map<string,any>(),agents:any[]=[],history:any[]=[];
const response=(res:any,data:any)=>res.json({success:true,data:{...data,simulated:true},timestamp:Date.now()});
app.get('/health',(_req,res)=>res.json({status:'healthy',network:'demo',service:'aegix-gateway'}));
app.get('/api/status',(_req,res)=>response(res,{version:'1.1.0-restored',mode:'demo',network:'demo',usdc_mint:null,fhe:{provider:'Demo',mode:'SIMULATION',sdkLoaded:false},payai:{network:'demo',features:[]}}));
app.get('/api/credits/stealth/stats',(_req,res)=>response(res,{totalPayments:history.length,totalVolume:0,activePools:pools.size}));
app.get('/api/agents/light/health',(_req,res)=>response(res,{healthy:false,error:'Demo makes no blockchain requests'}));
app.get('/api/credits/recovery/status',(_req,res)=>response(res,{initialized:false,address:null,balance:0,isHealthy:false,status:'NOT_INITIALIZED'}));
app.get('/api/credits/pool/:owner',(req,res)=>{const pool=pools.get(req.params.owner);if(pool)response(res,pool);else res.json({success:true,data:null,simulated:true});});
app.post('/api/credits/pool/init',(req,res)=>{const data={exists:true,poolId:randomUUID(),poolAddress:req.body.owner,publicKey:req.body.owner,status:'created',balance:{sol:0,usdc:0,compressedUsdc:0},totalPayments:0,totalSolRecovered:0,isNew:true};pools.set(req.body.owner,data);response(res,data);});
app.post('/api/credits/pool/fund',(req,res)=>{const p=pools.get(req.body.owner);if(!p){res.status(400).json({success:false,error:'Create a demo pool first'});return;}p.balance={sol:1,usdc:10,compressedUsdc:0};p.status='funded';response(res,{...p,confirmed:true});});
app.post('/api/credits/pool/pay',(req,res)=>{const p=pools.get(req.body.owner),amount=Number(req.body.amountUSDC);if(!p||!Number.isFinite(amount)||amount<=0||p.balance.usdc<amount){res.status(400).json({success:false,error:'Invalid amount or insufficient demo balance'});return;}p.balance.usdc-=amount;p.totalPayments++;history.push({id:randomUUID(),type:'demo_payment',amount:String(amount),timestamp:new Date().toISOString(),simulated:true});response(res,{paymentTx:null,tempBurnerAddress:'Demo burner — no blockchain wallet',poolBalance:p.balance,solRecovered:0,method:'demo'});});
app.get('/api/credits/audit/:owner',(_req,res)=>res.json({success:true,data:{logs:history},simulated:true}));
app.get('/api/credits/resources',(_req,res)=>res.json({success:true,data:[],simulated:true}));
app.post('/api/agents/register',(req,res)=>{const a={id:randomUUID(),owner:req.body.owner,name:req.body.name,status:'active',privacyLevel:'standard',spent24h:'0',totalSpent:'0',apiCalls:0,createdAt:new Date().toISOString(),lastActivity:new Date().toISOString(),apiKey:'demo-no-signing-authority'};agents.push(a);response(res,a);});
app.get('/api/agents/:owner',(_req,res)=>res.json({success:true,data:agents,simulated:true}));
app.use((_req,res)=>res.status(409).json({success:false,error:'This action is not available in demo mode; no blockchain transaction was sent',simulated:true}));
app.listen(Number(process.env.PORT||3705),process.env.HOST || '127.0.0.1',()=>console.log('Original Aegix demo backend ready'));
