const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),ts=require('typescript');
const root=path.resolve(__dirname,'..');
function load(file,extra={}){const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};const ctx={exports,require,process:{env:{}},Response,Headers,AbortSignal,TextEncoder,console,...extra};vm.runInNewContext(code,ctx);return exports;}
(async()=>{
 let signed=0;
 const runtime=load('packages/dashboard/src/lib/original-runtime.ts',{document:{cookie:''},fetch:async()=>Response.json({error:'Gateway offline'},{status:503})});runtime.setOriginalSigner('test-owner',async()=>{signed++;return new Uint8Array()});await assert.rejects(runtime.originalFetch('/api/gateway/api/credits/pool/init',{method:'POST'}),/Gateway offline/);assert.equal(signed,0);
 let forwarded='';const route=load('packages/dashboard/src/app/api/gateway/[...path]/route.ts',{process:{env:{VERCEL:'1'}},fetch:async url=>{forwarded=url;return Response.json({ok:true})}});const request={cookies:{get:()=>({value:'devnet'})},headers:new Headers(),method:'GET',nextUrl:{search:''}};assert.equal((await route.GET(request,{params:{path:['health']}})).status,503);assert.equal(forwarded,'');
 const configured=load('packages/dashboard/src/app/api/gateway/[...path]/route.ts',{process:{env:{VERCEL:'1',AEGIX_DEVNET_GATEWAY_URL:'https://gateway.example/'}},fetch:async url=>{forwarded=url;return Response.json({ok:true})}});assert.equal((await configured.GET(request,{params:{path:['health']}})).status,200);assert.equal(forwarded,'https://gateway.example/health');
 const rpc=load('packages/dashboard/src/app/api/rpc/route.ts',{process:{env:{HELIUS_API_KEY:'test-key'}},fetch:async url=>{forwarded=url;return Response.json({result:1})}});await rpc.POST({...request,json:async()=>({method:'getSlot',id:1})});assert.equal(forwarded,'https://devnet.helius-rpc.com/?api-key=test-key');
 assert.match(fs.readFileSync(path.join(root,'packages/dashboard/src/app/page.tsx'),'utf8'),/landing\/page/);assert.match(fs.readFileSync(path.join(root,'packages/dashboard/src/app/landing/page.tsx'),'utf8'),/push\('\/dashboard'\)/);console.log('PASS: no signing on gateway failure; hosted gateway routing; missing configuration; Helius key expansion; landing routes');
})().catch(e=>{console.error(e);process.exitCode=1});
